### PR TITLE
Be able to get the current user info

### LINKED ISSUE #34: Mismatch in getting user info
## Mismatch in getting user info
- Currently, api `/api/v1/login` only return `token` and api `/api/v1/users/{id}` only accept `userid`. 
- There's no way for FE to get user info with only `token`

## Environment
- Version: `93ba7a5020a515b8e0e94153571a7c1858069981`

## Steps to reproduce
- Always reproduce
- Follow the above order of APIs calling

## Expected behaviour
- Be able to get the user info with `token`

## Actual behaviour
- Get all users if no `<userid>` included

### PR DESCRIPTION
**Pull request by dothanhlam97**
api  /user/{user_id} 
```
if user_id = null then
   return current user
else
   return user whose id = user_id
```

### CODE REVIEW

File: controller/user.js [hunk 1]
```diff
@@ -83,8 +83,14 @@ async function getAll(req, res) {
...
 async function getById(req, res) {
-  const id = getIdParam(req);
-  const user = await models.User.findByPk(id);
+  let user_id;
+  if (!req.params.id) {
+    user_id = req.user.id;
+  } else {
+    user_id = getIdParam(req);
+  }
+  console.log(user_id);
```
Comment (hnngo) [inline controller/user.js]: Remove this

File: controller/user.js [hunk 2]
```diff
@@ -83,8 +83,14 @@ async function getAll(req, res) {
...
 
 async function getById(req, res) {
-  const id = getIdParam(req);
-  const user = await models.User.findByPk(id);
+  let user_id;
+  if (!req.params.id) {
+    user_id = req.user.id;
+  } else {
+    user_id = getIdParam(req);
+  }
```
Comment (hnngo) [inline controller/user.js]:
```suggestion
  const user_id = !req.params.id ? req.user.id : getIdParam(req)
```

**Review by hnngo — CHANGES_REQUESTED** [review]

**Review by hnngo — APPROVED** [review]

**Review by ndkhaivn — APPROVED** [review]
